from app.routes.auth import auth_bp
from app.routes.main import main_bp
from app.routes.servicios import servicios_bp
from app.routes.reservas import reservas_bp
from app.routes.promociones import promociones_bp
from app.routes.planificador import planificador_bp
from app.routes.solicitudes import solicitudes_bp
from app.routes.proveedores import proveedores_bp
from app.routes.transacciones import transacciones_bp